---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-16.04
  driver_config:
    box: opscode-ubuntu-16.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-16.04_chef-provisionerless.box

suites:
  - name: default
    data_bags_path: "test/integration/default/data_bags"
    driver:
      vm_hostname: jenkins.infralovers.consulting
      network:
      - ["private_network", {ip: "10.11.12.40"}]
      customize:
        memory: 1024
    run_list:
      - recipe[chatops_demo::default]
    attributes:
      lita:
        name: "r2d2"
        mention_name: "r2d2"
      chatops_demo:

